// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Animal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AgeInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVetChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = "animal-guid-1",
                            AgeInMonths = 14,
                            Breed = "Assaf",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy, high-grade breeding ram. Fully vaccinated.",
                            Gender = "Male",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Irbid, Jordan",
                            Name = "Assaf Ram",
                            OwnerId = "user-owner-guid-1",
                            Price = 350.00m,
                            SpeciesId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = "animal-guid-3",
                            AgeInMonths = 22,
                            Breed = "Awassi",
                            CreatedAt = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy Awassi ewe suitable for breeding. Good milk production.",
                            Gender = "Female",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Mafraq, Jordan",
                            Name = "Awassi Ewe",
                            OwnerId = "user-owner-guid-4",
                            Price = 280.00m,
                            SpeciesId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-4",
                            AgeInMonths = 6,
                            Breed = "Awassi",
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Young Awassi lamb with excellent body condition.",
                            Gender = "Male",
                            IsVerified = false,
                            IsVetChecked = false,
                            Location = "Irbid, Jordan",
                            Name = "Young Awassi Lamb",
                            OwnerId = "user-owner-guid-5",
                            Price = 150.00m,
                            SpeciesId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-5",
                            AgeInMonths = 30,
                            Breed = "Damascus (Shami)",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Large Shami goat with excellent milk production history.",
                            Gender = "Female",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Zarqa, Jordan",
                            Name = "Shami Doe",
                            OwnerId = "user-owner-guid-5",
                            Price = 450.00m,
                            SpeciesId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-6",
                            AgeInMonths = 18,
                            Breed = "Boer",
                            CreatedAt = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Strong Boer buck suitable for breeding and meat production.",
                            Gender = "Male",
                            IsVerified = true,
                            IsVetChecked = false,
                            Location = "Mafraq, Jordan",
                            Name = "Boer Buck",
                            OwnerId = "user-owner-guid-4",
                            Price = 520.00m,
                            SpeciesId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = "animal-guid-7",
                            AgeInMonths = 8,
                            Breed = "Shami",
                            CreatedAt = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Young healthy Shami goat with good growth potential.",
                            Gender = "Male",
                            IsVerified = false,
                            IsVetChecked = true,
                            Location = "Salt, Jordan",
                            Name = "Young Shami Goat",
                            OwnerId = "user-buyer-guid-8",
                            Price = 190.00m,
                            SpeciesId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-8",
                            AgeInMonths = 48,
                            Breed = "Holstein",
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-producing dairy cow with healthy udder and excellent milk history.",
                            Gender = "Female",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Irbid, Jordan",
                            Name = "Holstein Dairy Cow",
                            OwnerId = "user-owner-guid-1",
                            Price = 1800.00m,
                            SpeciesId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-9",
                            AgeInMonths = 9,
                            Breed = "Baladi",
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy young calf, ideal for small farms.",
                            Gender = "Male",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Jerash, Jordan",
                            Name = "Baladi Calf",
                            OwnerId = "user-buyer-guid-9",
                            Price = 850.00m,
                            SpeciesId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-10",
                            AgeInMonths = 72,
                            Breed = "Dromedary",
                            CreatedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Strong healthy Arabian camel suitable for breeding and farm use.",
                            Gender = "Male",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Mafraq, Jordan",
                            Name = "Arabian Camel",
                            OwnerId = "user-owner-guid-4",
                            Price = 3200.00m,
                            SpeciesId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = "animal-guid-11",
                            AgeInMonths = 36,
                            Breed = "Dromedary",
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Young female camel with good health indicators.",
                            Gender = "Female",
                            IsVerified = false,
                            IsVetChecked = false,
                            Location = "Azraq, Jordan",
                            Name = "Young Female Camel",
                            OwnerId = "user-owner-guid-5",
                            Price = 2900.00m,
                            SpeciesId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-2",
                            AgeInMonths = 24,
                            Breed = "Straight Egyptian",
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Purebred young Arabian horse with excellent temperament.",
                            Gender = "Female",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Amman, Jordan",
                            Name = "Arabian Filly",
                            OwnerId = "user-owner-guid-1",
                            Price = 2500.00m,
                            SpeciesId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-12",
                            AgeInMonths = 60,
                            Breed = "Arabian",
                            CreatedAt = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Well-trained Arabian stallion with strong bloodline and excellent movement.",
                            Gender = "Male",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Amman, Jordan",
                            Name = "Arabian Stallion",
                            OwnerId = "user-owner-guid-6",
                            Price = 7500.00m,
                            SpeciesId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = "animal-guid-13",
                            AgeInMonths = 84,
                            Breed = "Arabian",
                            CreatedAt = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Experienced Arabian mare with calm temperament.",
                            Gender = "Female",
                            IsVerified = true,
                            IsVetChecked = false,
                            Location = "Salt, Jordan",
                            Name = "Chestnut Mare",
                            OwnerId = "user-owner-guid-6",
                            Price = 4200.00m,
                            SpeciesId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-14",
                            AgeInMonths = 54,
                            Breed = "Baladi",
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Strong working donkey suitable for farm transportation.",
                            Gender = "Male",
                            IsVerified = false,
                            IsVetChecked = true,
                            Location = "Jerash, Jordan",
                            Name = "Baladi Donkey",
                            OwnerId = "user-owner-guid-5",
                            Price = 650.00m,
                            SpeciesId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-15",
                            AgeInMonths = 20,
                            Breed = "Local",
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Young healthy donkey with calm behavior.",
                            Gender = "Female",
                            IsVerified = false,
                            IsVetChecked = false,
                            Location = "Irbid, Jordan",
                            Name = "Young Donkey",
                            OwnerId = "user-owner-guid-1",
                            Price = 500.00m,
                            SpeciesId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-16",
                            AgeInMonths = 8,
                            Breed = "Rhode Island Red",
                            CreatedAt = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy rooster suitable for breeding.",
                            Gender = "Male",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Zarqa, Jordan",
                            Name = "Rhode Island Rooster",
                            OwnerId = "user-owner-guid-5",
                            Price = 35.00m,
                            SpeciesId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-17",
                            AgeInMonths = 10,
                            Breed = "Rhode Island Red",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy laying hen with good egg production.",
                            Gender = "Female",
                            IsVerified = true,
                            IsVetChecked = true,
                            Location = "Irbid, Jordan",
                            Name = "Rhode Island Hen",
                            OwnerId = "user-owner-guid-1",
                            Price = 30.00m,
                            SpeciesId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = "animal-guid-18",
                            AgeInMonths = 7,
                            Breed = "Broad Breasted White",
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy large turkey suitable for farm breeding.",
                            Gender = "Male",
                            IsVerified = false,
                            IsVetChecked = false,
                            Location = "Mafraq, Jordan",
                            Name = "Broad Breasted Turkey",
                            OwnerId = "user-owner-guid-4",
                            Price = 80.00m,
                            SpeciesId = 3,
                            Status = 2
                        });
                });

            modelBuilder.Entity("WebApp.Models.AnimalImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("AnimalImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = "animal-guid-1",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = "animal-guid-1",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = false
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = "animal-guid-2",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = "animal-guid-3",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = "animal-guid-4",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = "animal-guid-5",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = "animal-guid-6",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = "animal-guid-7",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = "animal-guid-8",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = "animal-guid-9",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = "animal-guid-10",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = "animal-guid-11",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 13,
                            AnimalId = "animal-guid-12",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 14,
                            AnimalId = "animal-guid-13",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 15,
                            AnimalId = "animal-guid-14",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 16,
                            AnimalId = "animal-guid-15",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 17,
                            AnimalId = "animal-guid-16",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 18,
                            AnimalId = "animal-guid-17",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        },
                        new
                        {
                            Id = 19,
                            AnimalId = "animal-guid-18",
                            ImageUrl = "/images/animals/placeholder.jfif",
                            IsMain = true
                        });
                });

            modelBuilder.Entity("WebApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VerificationDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-owner-guid-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e49ccae4-2d95-4e73-82ad-fe4bf1414b8c",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmad@example.com",
                            EmailConfirmed = true,
                            FullName = "Ahmad Al-Farmawi",
                            IsVerified = true,
                            Location = "Irbid, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMAD@EXAMPLE.COM",
                            NormalizedUserName = "AHMAD_FARMER",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e49ccae4-2d95-4e73-82ad-fe4bf1414b8c",
                            TwoFactorEnabled = false,
                            UserName = "ahmad_farmer"
                        },
                        new
                        {
                            Id = "user-bidder-guid-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e34de3c3-3ac8-423a-8a1b-6abd62098c13",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sami@example.com",
                            EmailConfirmed = true,
                            FullName = "Sami Al-Khatib",
                            IsVerified = true,
                            Location = "Amman, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "SAMI@EXAMPLE.COM",
                            NormalizedUserName = "SAMI_BUYER",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e34de3c3-3ac8-423a-8a1b-6abd62098c13",
                            TwoFactorEnabled = false,
                            UserName = "sami_buyer"
                        },
                        new
                        {
                            Id = "user-vet-guid-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b77ad96-eaca-4af0-a5da-8a05e6d2ecb4",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rami.vet@example.com",
                            EmailConfirmed = true,
                            FullName = "Dr. Rami Naser",
                            IsVerified = true,
                            Location = "Irbid, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "RAMI.VET@EXAMPLE.COM",
                            NormalizedUserName = "DR_RAMI",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b77ad96-eaca-4af0-a5da-8a05e6d2ecb4",
                            TwoFactorEnabled = false,
                            UserName = "dr_rami"
                        },
                        new
                        {
                            Id = "user-owner-guid-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000004",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "yousef@example.com",
                            EmailConfirmed = true,
                            FullName = "Yousef Haddad",
                            IsVerified = true,
                            Location = "Mafraq, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "YOUSEF@EXAMPLE.COM",
                            NormalizedUserName = "YOUSEF_LIVESTOCK",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10000000-0000-0000-0000-000000000004",
                            TwoFactorEnabled = false,
                            UserName = "yousef_livestock"
                        },
                        new
                        {
                            Id = "user-owner-guid-5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000005",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar@example.com",
                            EmailConfirmed = true,
                            FullName = "Omar Al-Zoubi",
                            IsVerified = false,
                            Location = "Zarqa, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR@EXAMPLE.COM",
                            NormalizedUserName = "OMAR_FARM",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10000000-0000-0000-0000-000000000005",
                            TwoFactorEnabled = false,
                            UserName = "omar_farm"
                        },
                        new
                        {
                            Id = "user-owner-guid-6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000006",
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "khaled@example.com",
                            EmailConfirmed = true,
                            FullName = "Khaled Al-Rashdan",
                            IsVerified = true,
                            Location = "Amman, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "KHALED@EXAMPLE.COM",
                            NormalizedUserName = "KHALED_HORSES",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10000000-0000-0000-0000-000000000006",
                            TwoFactorEnabled = false,
                            UserName = "khaled_horses"
                        },
                        new
                        {
                            Id = "user-buyer-guid-7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000007",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali@example.com",
                            EmailConfirmed = true,
                            FullName = "Ali Saleh",
                            IsVerified = true,
                            Location = "Amman, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI@EXAMPLE.COM",
                            NormalizedUserName = "ALI_BUYER",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10000000-0000-0000-0000-000000000007",
                            TwoFactorEnabled = false,
                            UserName = "ali_buyer"
                        },
                        new
                        {
                            Id = "user-buyer-guid-8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000008",
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohammad@example.com",
                            EmailConfirmed = true,
                            FullName = "Mohammad Ahmad",
                            IsVerified = false,
                            Location = "Salt, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "MOHAMMAD@EXAMPLE.COM",
                            NormalizedUserName = "MOHAMMAD_FARMER",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10000000-0000-0000-0000-000000000008",
                            TwoFactorEnabled = false,
                            UserName = "mohammad_farmer"
                        },
                        new
                        {
                            Id = "user-buyer-guid-9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000009",
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fadi@example.com",
                            EmailConfirmed = true,
                            FullName = "Fadi Nassar",
                            IsVerified = true,
                            Location = "Jerash, Jordan",
                            LockoutEnabled = false,
                            NormalizedEmail = "FADI@EXAMPLE.COM",
                            NormalizedUserName = "FADI_ANIMALS",
                            PasswordHash = "PREGENERATED_HASH_1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10000000-0000-0000-0000-000000000009",
                            TwoFactorEnabled = false,
                            UserName = "fadi_animals"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VetProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VetProfileId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = "appointment-guid-1",
                            ClientId = "user-bidder-guid-2",
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Routine checkup for a new calf.",
                            RequestedDate = new DateTime(2026, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VetProfileId = "vet-profile-id-1"
                        },
                        new
                        {
                            Id = "appointment-guid-2",
                            ClientId = "user-buyer-guid-7",
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Pre-purchase veterinary examination for Boer goat.",
                            RequestedDate = new DateTime(2026, 3, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VetProfileId = "vet-profile-id-1"
                        },
                        new
                        {
                            Id = "appointment-guid-3",
                            ClientId = "user-buyer-guid-8",
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Camel health examination and vaccination review.",
                            RequestedDate = new DateTime(2026, 3, 12, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VetProfileId = "vet-profile-id-1"
                        },
                        new
                        {
                            Id = "appointment-guid-4",
                            ClientId = "user-buyer-guid-9",
                            CreatedAt = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "General examination of Arabian stallion before auction.",
                            RequestedDate = new DateTime(2026, 3, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VetProfileId = "vet-profile-id-1"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Auction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HighestBidderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LotNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LotNumber"));

                    b.Property<decimal>("MinIncrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique();

                    b.HasIndex("HighestBidderId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = "auction-guid-1",
                            AnimalId = "animal-guid-1",
                            CurrentPrice = 320.00m,
                            EndTime = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            HighestBidderId = "user-bidder-guid-2",
                            LotNumber = 0,
                            MinIncrement = 10.00m,
                            StartTime = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 300.00m,
                            Status = 1,
                            Title = "Auction1"
                        },
                        new
                        {
                            Id = "auction-guid-2",
                            AnimalId = "animal-guid-6",
                            CurrentPrice = 500.00m,
                            EndTime = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            HighestBidderId = "user-buyer-guid-7",
                            LotNumber = 0,
                            MinIncrement = 10.00m,
                            StartTime = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 450.00m,
                            Status = 1,
                            Title = "Auction2"
                        },
                        new
                        {
                            Id = "auction-guid-3",
                            AnimalId = "animal-guid-10",
                            CurrentPrice = 3100.00m,
                            EndTime = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            HighestBidderId = "user-buyer-guid-8",
                            LotNumber = 0,
                            MinIncrement = 50.00m,
                            StartTime = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 2800.00m,
                            Status = 1,
                            Title = "Auction3"
                        },
                        new
                        {
                            Id = "auction-guid-4",
                            AnimalId = "animal-guid-12",
                            CurrentPrice = 7000.00m,
                            EndTime = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HighestBidderId = "user-buyer-guid-9",
                            LotNumber = 0,
                            MinIncrement = 100.00m,
                            StartTime = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 6500.00m,
                            Status = 1,
                            Title = "Auction4"
                        },
                        new
                        {
                            Id = "auction-guid-5",
                            AnimalId = "animal-guid-18",
                            CurrentPrice = 70.00m,
                            EndTime = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            HighestBidderId = "user-bidder-guid-2",
                            LotNumber = 0,
                            MinIncrement = 5.00m,
                            StartTime = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 60.00m,
                            Status = 1,
                            Title = "Auction5"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AuctionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 310.00m,
                            AuctionId = "auction-guid-1",
                            PlacedAt = new DateTime(2026, 3, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 320.00m,
                            AuctionId = "auction-guid-1",
                            PlacedAt = new DateTime(2026, 3, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-7"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 460.00m,
                            AuctionId = "auction-guid-2",
                            PlacedAt = new DateTime(2026, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 480.00m,
                            AuctionId = "auction-guid-2",
                            PlacedAt = new DateTime(2026, 3, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-7"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 500.00m,
                            AuctionId = "auction-guid-2",
                            PlacedAt = new DateTime(2026, 3, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-8"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 2900.00m,
                            AuctionId = "auction-guid-3",
                            PlacedAt = new DateTime(2026, 3, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-8"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 3000.00m,
                            AuctionId = "auction-guid-3",
                            PlacedAt = new DateTime(2026, 3, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 3100.00m,
                            AuctionId = "auction-guid-3",
                            PlacedAt = new DateTime(2026, 3, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-8"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 6700.00m,
                            AuctionId = "auction-guid-4",
                            PlacedAt = new DateTime(2026, 3, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-9"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 6900.00m,
                            AuctionId = "auction-guid-4",
                            PlacedAt = new DateTime(2026, 3, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 7000.00m,
                            AuctionId = "auction-guid-4",
                            PlacedAt = new DateTime(2026, 3, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-9"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 65.00m,
                            AuctionId = "auction-guid-5",
                            PlacedAt = new DateTime(2026, 3, 8, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 70.00m,
                            AuctionId = "auction-guid-5",
                            PlacedAt = new DateTime(2026, 3, 8, 13, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-buyer-guid-7"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = "animal-guid-1",
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = "animal-guid-2",
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = "animal-guid-12",
                            UserId = "user-bidder-guid-2"
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = "animal-guid-6",
                            UserId = "user-buyer-guid-7"
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = "animal-guid-8",
                            UserId = "user-buyer-guid-7"
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = "animal-guid-10",
                            UserId = "user-buyer-guid-8"
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = "animal-guid-11",
                            UserId = "user-buyer-guid-8"
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = "animal-guid-12",
                            UserId = "user-buyer-guid-9"
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = "animal-guid-13",
                            UserId = "user-buyer-guid-9"
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = "animal-guid-8",
                            UserId = "user-owner-guid-1"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sheep, goats, cows, and camels",
                            IconUrl = "/images/species/livestock.png",
                            Name = "Livestock"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Horses, donkeys, and ponies",
                            IconUrl = "/images/species/equine.png",
                            Name = "Equine"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chickens, ducks, and turkeys",
                            IconUrl = "/images/species/poultry.png",
                            Name = "Poultry"
                        });
                });

            modelBuilder.Entity("WebApp.Models.VetProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ClinicLocation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VetProfiles");

                    b.HasData(
                        new
                        {
                            Id = "vet-profile-id-1",
                            Bio = "Experienced large animal veterinarian with over 10 years of practice in northern Jordan.",
                            ClinicLocation = "Irbid Veterinary Clinic, Main Street",
                            IsVerified = true,
                            LicenseDocumentUrl = "/docs/licenses/vet_rami.pdf",
                            Specialty = "Livestock & Equine",
                            UserId = "user-vet-guid-3",
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Models.Animal", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", "Owner")
                        .WithMany("Animals")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("WebApp.Models.AnimalImage", b =>
                {
                    b.HasOne("WebApp.Models.Animal", "Animal")
                        .WithMany("Images")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("WebApp.Models.Appointment", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", "Client")
                        .WithMany("AppointmentsAsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.VetProfile", "VetProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("VetProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("VetProfile");
                });

            modelBuilder.Entity("WebApp.Models.Auction", b =>
                {
                    b.HasOne("WebApp.Models.Animal", "Animal")
                        .WithOne("Auction")
                        .HasForeignKey("WebApp.Models.Auction", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ApplicationUser", "HighestBidder")
                        .WithMany()
                        .HasForeignKey("HighestBidderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Animal");

                    b.Navigation("HighestBidder");
                });

            modelBuilder.Entity("WebApp.Models.Bid", b =>
                {
                    b.HasOne("WebApp.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ApplicationUser", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp.Models.Favorite", b =>
                {
                    b.HasOne("WebApp.Models.Animal", "Animal")
                        .WithMany("Favorites")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ApplicationUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp.Models.VetProfile", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", "User")
                        .WithOne("VetProfile")
                        .HasForeignKey("WebApp.Models.VetProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp.Models.Animal", b =>
                {
                    b.Navigation("Auction");

                    b.Navigation("Favorites");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("WebApp.Models.ApplicationUser", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("AppointmentsAsClient");

                    b.Navigation("Bids");

                    b.Navigation("Favorites");

                    b.Navigation("VetProfile");
                });

            modelBuilder.Entity("WebApp.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("WebApp.Models.Species", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("WebApp.Models.VetProfile", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
